# 工作流的名称
name: Build System Informer Release (Direct MSBuild)

# 触发工作流的事件
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    # 使用最新的 Windows 虚拟机环境
    runs-on: windows-latest

    steps:
      # 第一步：检出代码和所有子模块
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 第二步：设置 NuGet (用于恢复项目包)
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # 第三步：设置 MSBuild 环境
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      # 第四步：恢复解决方案的 NuGet 包
      # 这是一个标准的预备步骤，确保所有外部依赖项都已下载
      - name: Restore NuGet packages
        run: nuget restore SystemInformer.sln

      # 第五步：直接使用 MSBuild 编译整个解决方案
      # 这是最核心的改变。我们直接调用 msbuild，不再使用 .cmd 脚本
      - name: Build Solution with MSBuild
        run: msbuild SystemInformer.sln -p:Configuration=Release -p:Platform=Win32 /m

      # 第六步：上传构建好的文件
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SystemInformer-Binary-Win32
          # 输出路径应该保持不变
          path: bin/Release32/
