# 工作流的名称，会显示在 Actions 页面
name: Build System Informer Release

# 触发工作流的事件
on:
  # 允许你手动从 GitHub 网页上点击按钮来触发构建
  workflow_dispatch:

  # （可选）每当你向 main 分支推送代码时，也会自动触发构建
  push:
    branches:
      - main

jobs:
  build:
    # 指定运行此任务的虚拟机环境，使用最新的 Windows Server
    runs-on: windows-latest

    steps:
      # 第一步：检出（下载）你的仓库代码到虚拟机
      # 这是标准操作
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 关键！我们之前发现项目有子模块，这里会自动拉取它们
          submodules: 'recursive'

      # 第二步：设置 MSBuild 环境
      # 这个 action 会自动找到 Visual Studio 的 msbuild.exe 并将其添加到系统路径
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      # 第三步：运行初始化脚本
      # 和你在本地做的一样，运行官方的初始化命令
      - name: Run Build Initialization
        run: .\build_init.cmd
        shell: cmd

      # 第四步：运行发布构建脚本
      # 和你在本地做的一样，运行官方的构建命令
      - name: Run Release Build
        run: .\build_release.cmd
        shell: cmd

      # 第五步：上传构建产物
      # 将构建生成的文件打包，以便你下载
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          # 打包后的 zip 文件名
          name: SystemInformer-Binary
          # 需要打包上传的文件夹路径，构建产物通常在 'bin' 目录下
          path: bin/
