# 工作流的名称
name: Build System Informer (Official Method)

# 触发工作流的事件
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    # 使用最新的 Windows 虚拟机环境
    runs-on: windows-latest

    steps:
      # 第一步：检出代码和所有子模块
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # 第二步：设置 MSBuild 环境 (脚本需要它)
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      # 第三步：运行初始化脚本 (关键步骤)
      # 这一步会编译项目所需的自定义工具, 例如 CustomBuildTool.exe
      - name: Run Build Initialization
        run: .\build\build_init.cmd
        shell: cmd

      # 第四步：运行发布构建脚本
      # 现在初始化已完成, 此脚本可以找到所有工具和依赖项
      - name: Run Release Build
        run: .\build\build_release.cmd
        shell: cmd

      # 第五步：上传构建好的文件
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SystemInformer-Binary-Win32
          path: bin/Release32/
