# 工作流的名称
name: Build System Informer (Official Method)

# 触发工作流的事件
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    # 使用官方指定的 Windows 虚拟机环境
    runs-on: windows-latest

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 保留子模块拉取，这是个好习惯
          submodules: 'recursive'

      # 第二步 (新增): 设置 NuGet 环境
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      # 第三步 (新增): 缓存 NuGet 包以加快未来构建速度
      - name: NuGet Cache
        uses: actions/cache@v4
        with:
          path: packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.config') }}

      # 第四步 (关键): 恢复 NuGet 包
      # 这是我们之前缺失的关键步骤, 它会下载项目所需的外部库
      - name: Nuget Restore
        run: nuget restore .\packages.config -PackagesDirectory .\packages\
        shell: cmd

      # 第五步：运行初始化脚本
      - name: Run Build Initialization
        run: build\build_init.cmd
        shell: cmd

      # 第六步：运行发布构建脚本
      - name: Run Release Build
        run: build\build_release.cmd
        shell: cmd

      # 第七步：上传构建好的文件
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SystemInformer-Binary-Win32
          path: bin/Release32/
